rem System : Demo: Sport Goods Orders
rem Descrip: Changes to original scripts
rem Author : Alejandro Flores-Solis
rem Date   : 15/10/2022

alter table S_PRODUCT add (IMAGE BLOB);

alter table S_PRODUCT add (SPORT VARCHAR2(30));

update S_PRODUCT set SPORT = 'Ski'
where  NAME like '%Ski%';

update S_PRODUCT set SPORT = 'Cycling'
where  NAME like '%Bicycle%';

update S_PRODUCT set SPORT = 'Soccer'
where  NAME like '%Soccer%';

update S_PRODUCT set SPORT = 'Baseball'
where  NAME like '%Baseball%'
or     NAME like '%Glove%'
or     NAME like '%Bat%';

update S_PRODUCT set SPORT = 'Gym Equipment'
where  NAME like '%Weight%'
or     NAME like '%Bar%';


alter table S_CUSTOMER add (
  LATITUDE              number,
  LONGITUDE             number
);


create table S_USERS (
  ID                    number generated by default on null as identity,
  USERNAME              varchar2(50),
  PASSWORD              varchar2(50),
  ROLE                  varchar2(20)
);
alter table S_USERS add constraint S_USERS_PK  primary key (ID) using index;
alter table S_USERS add constraint S_USERS_UK1 unique (USERNAME) using index;


create or replace function S_USER_AUTH (
  p_username       varchar2,
  p_password       varchar2
) return boolean IS
  vFound          number;
BEGIN
  select 1
  into   vFound
  from   S_USERS
  where  USERNAME = p_username
  and    PASSWORD = p_password;

  return (true);

EXCEPTION
  when NO_DATA_FOUND then
    apex_util.set_custom_auth_status(p_status => 'You do not have grants to access this application. <br>Please contact the system administrator'); 
    return FALSE; 
END;
/
